apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    cluster.storage.openshift.io/owner-name: cluster-config-v1
    cluster.storage.openshift.io/owner-namespace: kube-system
  name: gp3
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
