apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: datetime
spec:
  schedule: "* * * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: datetime
            image: busybox
            command: ["/bin/sh"]
            args:
              - "-c"
              - date
          restartPolicy: Never
